/**
 * i18n feature module: Landing page strings (brand, hero, problem, solution, features, FAQ, footer, etc.).
 * Auto-generated by scripts/split-i18n.mjs — edit keys here as needed.
 */

export const enLanding: Record<string, string> = {  /* ---------- Brand ---------- */
  "brand.name": "Kissan AI",
  "brand.tagline": "Your AI Farming Decision Assistant",

    /* ---------- Landing nav ---------- */
  "nav.home": "Home",
  "nav.features": "Features",
  "nav.howItWorks": "How It Works",
  "nav.problem": "Problem",
  "nav.solution": "Solution",
  "nav.about": "About",
  "nav.faq": "FAQ",
  "nav.contact": "Contact",
  "nav.login": "Log in",
  "nav.getStarted": "Get Started",
  "nav.openMenu": "Open menu",
  "nav.closeMenu": "Close menu",
  "nav.main": "Main",
  "nav.primary": "Primary",
  "nav.aiTools": "AI Tools",
  "nav.manage": "Manage",
  "nav.bottom": "Bottom",
  "nav.more": "More",

    /* ---------- Landing: hero ---------- */
  "hero.badge": "AI Powered Farming Dashboard",
  "hero.titleA": "Smart Farming.",
  "hero.titleB": "Better Decisions.",
  "hero.titleC": "Higher Yields.",
  "hero.subtitle":
    "Kissan AI helps farmers diagnose crop issues, get real-time weather insights, plan irrigation, and receive intelligent AI recommendations.",
  "hero.cta": "Get Started Free",
  "hero.explore": "Learn More",
  "hero.h1": "Farm-centric",
  "hero.h1Text":
    "Guidance tailored to your crops, soil, and location — not generic advice.",
  "hero.h2": "Spot problems early",
  "hero.h2Text":
    "Upload a photo of a sick leaf and understand what may be happening.",
  "hero.h3": "Ask in your language",
  "hero.h3Text": "Talk or type in Urdu, English, Punjabi, and more.",

    /* ---------- Landing: hero phone mockup ---------- */
  "hero.phone.cropDoctor": "AI Crop Doctor",
  "hero.phone.cropRecommendation": "Crop Recommendation",
  "hero.phone.irrigation": "Irrigation Advisor",
  "hero.phone.yield": "Yield Prediction",
  "hero.phone.history": "Farming History",

    /* ---------- Landing: statistics ---------- */
  "stats.sectionLabel": "Impact statistics",
  "stats.farmersLabel": "Farmers Helped",
  "stats.accuracyLabel": "Accuracy",
  "stats.cropsLabel": "Crops Supported",
  "stats.supportLabel": "AI Support",

    /* ---------- Landing: problem ---------- */
  "problem.eyebrow": "The Problem",
  "problem.title": "Farming is full of uncertainty",
  "problem.subtitle":
    "Smallholder farmers make life-critical decisions every day — but often with scattered, outdated, or generic information.",
  "problem.p1": "Unpredictable weather",
  "problem.p1Text":
    "Rain, heat, and frost arrive without warning, leaving farmers guessing when to plant, water, or harvest.",
  "problem.p2": "Pests and disease spread fast",
  "problem.p2Text":
    "By the time symptoms are visible, damage is often done. Early detection is the difference between saving and losing a crop.",
  "problem.p3": "Advice isn't local",
  "problem.p3Text":
    "Generic tips ignore your soil, your crop, your climate, and your calendar — so most advice simply doesn't apply to your farm.",
  "problem.p4": "Too many decisions, too little time",
  "problem.p4Text":
    "Between inputs, weather, and daily farm work, it's hard to know what actually matters today.",

    /* ---------- Landing: solution ---------- */
  "solution.eyebrow": "The Solution",
  "solution.title": "One clear picture of your farm — and what to do today",
  "solution.subtitle":
    "Kissan AI is a farm-centric decision engine. Instead of juggling apps, news, and guesswork, you get plain-language answers that reflect your crops, your weather, and your calendar.",
  "solution.s1": "Know your farm",
  "solution.s1Text":
    "Set up your farm once — location, crops, soil, and planting date — and every answer is grounded in that context.",
  "solution.s2": "Spot problems early",
  "solution.s2Text":
    "Upload a photo of a sick leaf and get a likely diagnosis with clear next steps before damage spreads.",
  "solution.s3": "Plan with the weather",
  "solution.s3Text":
    "See what the forecast actually means for your fields — when to water, spray, or hold off.",
  "solution.s4": "Ask in your language",
  "solution.s4Text":
    "Chat or speak in Urdu, English, Punjabi, and more. No jargon, no guesswork.",
  "solution.previewLabel": "Today on your farm",
  "solution.preview1Label": "Wheat · 62 days since planting",
  "solution.preview1Value": "Growth stage: Tillering",
  "solution.preview2Label": "Weather",
  "solution.preview2Value": "28°C · 40% chance of rain tonight",
  "solution.preview3Label": "Risk level",
  "solution.preview3Value": "Low — watch for aphids",
  "solution.preview4Label": "Today's action",
  "solution.preview4Value": "Delay watering until tomorrow's rain passes",
  "solution.previewNote": "Illustrative preview — shown once your farm data is available.",

    /* ---------- Landing: features ---------- */
  "features.eyebrow": "Features",
  "features.title": "Everything your farm needs, in one place",
  "features.subtitle":
    "From diagnosing a sick leaf to deciding today's work, Kissan AI turns complex farming decisions into simple guidance.",
  "features.f1": "AI Crop Doctor",
  "features.f1Text":
    "Upload a photo of an affected leaf and get a likely diagnosis with confidence, severity, and clear next steps.",
  "features.f2": "AI Assistant",
  "features.f2Text":
    "Ask anything about your farm in plain language and get answers grounded in your crops, soil, and season.",
  "features.f3": "Voice Assistant",
  "features.f3Text":
    "Speak naturally in Urdu, Punjabi, Saraiki, or English — no typing needed in the field.",
  "features.f4": "Weather Intelligence",
  "features.f4Text":
    "Understand what the forecast means for your farm — when to water, spray, or harvest.",
  "features.f5": "Risks & Alerts",
  "features.f5Text":
    "See low, medium, and high risks with clear explanations and the exact action to take.",
  "features.f6": "Today's Actions",
  "features.f6Text":
    "A short, prioritized list of what actually matters today — no more guessing.",
  "features.f7": "Yield Prediction",
  "features.f7Text":
    "See an expected yield range and the key factors driving it, so you can plan sales and inputs.",

    /* ---------- Landing: how it works ---------- */
  "how.eyebrow": "How It Works",
  "how.title": "From setup to action in four steps",
  "how.s1Title": "Set up your farm",
  "how.s1Text":
    "Enter your location, crops, soil, and planting date once — it takes minutes.",
  "how.s2Title": "Share what you see",
  "how.s2Text":
    "Upload a leaf photo, check the weather, or ask about a concern you have.",
  "how.s3Title": "Get clear answers",
  "how.s3Text":
    "Receive plain-language explanations in your language, tied to your farm.",
  "how.s4Title": "Act with confidence",
  "how.s4Text":
    "Follow a short list of prioritized actions for today and track your progress.",

    /* ---------- Landing: testimonials ---------- */
  "testimonials.eyebrow": "Testimonials",
  "testimonials.title": "Farmers trust Kissan AI",
  "testimonials.subtitle": "Real voices from farmers using Kissan AI in their fields.",
  "testimonials.q1":
    "I used to ask everyone for advice — neighbours, YouTube, sometimes even strangers. Kissan AI gives me an answer about MY farm, in my own language.",
  "testimonials.n1": "Muhammad Aslam",
  "testimonials.r1": "Wheat & cotton farmer, Punjab",
  "testimonials.q2":
    "The photo of my tomato leaves looked fine to me, but the diagnosis caught a fungus early. That one warning saved a big part of my crop.",
  "testimonials.n2": "Ayesha Bibi",
  "testimonials.r2": "Vegetable grower, Sindh",
  "testimonials.q3":
    "What I love is the 'today's actions' list. I open it in the morning and I know exactly what to do. It feels like having an expert in my pocket.",
  "testimonials.n3": "Rana Imran",
  "testimonials.r3": "Rice farmer, Khyber Pakhtunkhwa",
  "testimonials.stars": "5 out of 5 stars",

    /* ---------- Landing: FAQ ---------- */
  "faq.eyebrow": "FAQ",
  "faq.title": "Questions farmers ask us",
  "faq.subtitle": "Frequently asked questions about Kissan AI.",
  "faq.q1": "What is Kissan AI?",
  "faq.a1":
    "Kissan AI is an AI-powered farming decision assistant. It brings together your farm's crops, weather, risks, and expected yield into one clear picture — then tells you what to do today, in plain language.",
  "faq.q2": "Do I need to be tech-savvy to use it?",
  "faq.a2":
    "Not at all. Kissan AI is designed to be simple: big buttons, your own language, and even voice input. If you can send a message, you can use Kissan AI.",
  "faq.q3": "Which languages are supported?",
  "faq.a3":
    "You can chat and speak in Urdu, English, Punjabi, and Saraiki, with more on the way. Answers come back in the same language you use.",
  "faq.q4": "How accurate are the diagnoses and predictions?",
  "faq.a4":
    "Kissan AI gives you estimates and guidance to help you decide — never a guarantee. You'll always see confidence levels, and you should confirm critical cases with a local agricultural expert or extension officer.",
  "faq.q5": "Is my farm data private?",
  "faq.a5":
    "Yes. Your farm information is used only to personalise your guidance and is never sold or shared. You stay in control of your farm profile.",
  "faq.q6": "What do I need to get started?",
  "faq.a6":
    "Just set up your farm profile — location, crops, soil, and planting date. It takes a couple of minutes, and then every feature is tailored to your farm.",

    /* ---------- Landing: contact ---------- */
  "contact.eyebrow": "Contact",
  "contact.title": "Let's grow together",
  "contact.subtitle":
    "Have a question, partnership idea, or feedback? We'd love to hear from you — in Urdu, English, or any language you're comfortable with.",
  "contact.email": "Email",
  "contact.phone": "Phone / WhatsApp",
  "contact.basedIn": "Based in",
  "contact.basedInValue": "Lahore, Pakistan — built for farmers everywhere",
  "contact.formTitle": "Send us a message",
  "contact.name": "Your name",
  "contact.namePlaceholder": "e.g. Ahmad Khan",
  "contact.emailPhone": "Email or phone",
  "contact.emailPhonePlaceholder": "you@example.com or +92 3XX XXXXXXX",
  "contact.message": "Message",
  "contact.messagePlaceholder": "Tell us about your farm or your question…",
  "contact.send": "Send Message",
  "contact.replyNote": "We reply within 1–2 working days.",
  "contact.successTitle": "Shukriya — message received!",
  "contact.successText":
    "We've got your message and will get back to you soon. In the meantime, set up your farm and explore what Kissan AI can do.",

    /* ---------- Landing: footer ---------- */
  "footer.tagline":
    "Your AI farming decision assistant — understand your farm and know what to do today.",
  "footer.quickLinks": "Quick Links",
  "footer.product": "Product",
  "footer.company": "Company",
  "footer.rights": "All rights reserved.",

  };

export const urLanding: Record<string, string> = {  /* ---------- Brand ---------- */
  "brand.name": "کسان اے آئی",
  "brand.tagline": "آپ کا اے آئی فارمنگ فیصلہ اسسٹنٹ",

    /* ---------- Landing nav ---------- */
  "nav.home": "ہوم",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "یہ کیسے کام کرتا ہے",
  "nav.problem": "مسئلہ",
  "nav.solution": "حل",
  "nav.about": "ہمارے بارے میں",
  "nav.faq": "سوالات",
  "nav.contact": "رابطہ",
  "nav.login": "لاگ ان",
  "nav.getStarted": "شروع کریں",
  "nav.openMenu": "مینو کھولیں",
  "nav.closeMenu": "مینو بند کریں",
  "nav.main": "مینو",
  "nav.primary": "بنیادی",
  "nav.aiTools": "AI ٹولز",
  "nav.manage": "انتظام",
  "nav.bottom": "نیچے",
  "nav.more": "مزید",

    /* ---------- Landing: hero ---------- */
  "hero.badge": "اے آئی سے چلنے والا فارمنگ ڈیش بورڈ",
  "hero.titleA": "سمارٹ فارمنگ۔",
  "hero.titleB": "بہتر فیصلے۔",
  "hero.titleC": "زیادہ پیداوار۔",
  "hero.subtitle":
    "کسان اے آئی کسانوں کو فصل کے مسائل کی تشخیص، براہ راست موسمی معلومات، آبپاشی کی منصوبہ بندی اور ذہین اے آئی تجاویز فراہم کرتا ہے۔",
  "hero.cta": "مفت شروع کریں",
  "hero.explore": "مزید جانیں",
  "hero.h1": "فارم مرکوز",
  "hero.h1Text":
    "آپ کی فصلوں، مٹی اور مقام کے مطابق رہنمائی — عام مشورہ نہیں۔",
  "hero.h2": "مسئلہ جلد پکڑیں",
  "hero.h2Text":
    "بیمار پتے کی تصویر اپ لوڈ کریں اور جانئے کیا ہو سکتا ہے۔",
  "hero.h3": "اپنی زبان میں پوچھیں",
  "hero.h3Text": "اردو، انگریزی، پنجابی اور مزید میں لکھیں یا بولیں۔",

    /* ---------- Landing: hero phone mockup ---------- */
  "hero.phone.cropDoctor": "اے آئی فصل ڈاکٹر",
  "hero.phone.cropRecommendation": "فصل کی سفارش",
  "hero.phone.irrigation": "آبپاشی مشیر",
  "hero.phone.yield": "پیداوار کی پیش گوئی",
  "hero.phone.history": "فارمنگ ہسٹری",

    /* ---------- Landing: statistics ---------- */
  "stats.sectionLabel": "اثرات کے اعداد و شمار",
  "stats.farmersLabel": "کسانوں کی مدد کی",
  "stats.accuracyLabel": "درستگی",
  "stats.cropsLabel": "فصلیں معاون ہیں",
  "stats.supportLabel": "اے آئی معاونت",

    /* ---------- Landing: problem ---------- */
  "problem.eyebrow": "مسئلہ",
  "problem.title": "کھیتی باڑی غیر یقینی صورتحال سے بھری ہے",
  "problem.subtitle":
    "چھوٹے کسان ہر روز اہم فیصلے کرتے ہیں — لیکن اکثر بکھری، پرانی یا عام معلومات کے ساتھ۔",
  "problem.p1": "بے وقت موسم",
  "problem.p1Text":
    "بارش، گرمی اور پالا بغیر اطلاع کے آتے ہیں، جس سے کسان اندازہ نہیں لگا پاتے کہ کب بونا، پانی دینا یا فصل کاٹنی ہے۔",
  "problem.p2": "کیڑے اور بیماریاں تیزی سے پھیلتی ہیں",
  "problem.p2Text":
    "جب تک علامات نظر آتی ہیں، نقصان ہو چکا ہوتا ہے۔ جلد پتہ چلنا ہی فصل بچانے کی کلید ہے۔",
  "problem.p3": "مشورہ مقامی نہیں ہوتا",
  "problem.p3Text":
    "عام مشورے آپ کی مٹی، فصل، موسم اور تقویم کو نظر انداز کرتے ہیں — اس لیے زیادہ تر مشورہ آپ کے فارم پر لاگو نہیں ہوتا۔",
  "problem.p4": "بہت سارے فیصلے، بہت کم وقت",
  "problem.p4Text":
    "ادویات، موسم اور روزمرہ کے کام کے درمیان یہ جاننا مشکل ہے کہ آج واقعی کیا اہم ہے۔",

    /* ---------- Landing: solution ---------- */
  "solution.eyebrow": "حل",
  "solution.title": "آپ کے فارم کی ایک واضح تصویر — اور آج کیا کرنا ہے",
  "solution.subtitle":
    "کسان اے آئی ایک فارم مرکوز فیصلہ انجن ہے۔ ایپس، خبروں اور اندازوں کو جگل کرنے کی بجائے، آپ کو سادہ زبان میں جواب ملتے ہیں جو آپ کی فصلوں، موسم اور تقویم کی عکاسی کرتے ہیں۔",
  "solution.s1": "اپنے فارم کو جانیں",
  "solution.s1Text":
    "اپنا فارم ایک بار ترتیب دیں — مقام، فصلیں، مٹی اور بونے کی تاریخ — اور ہر جواب اسی سیاق سے جڑا ہوگا۔",
  "solution.s2": "مسئلہ جلد پکڑیں",
  "solution.s2Text":
    "بیمار پتے کی تصویر اپ لوڈ کریں اور نقصان پھیلنے سے پہلے ممکنہ تشخیص اور واضح اگلے اقدامات حاصل کریں۔",
  "solution.s3": "موسم کے ساتھ منصوبہ بنائیں",
  "solution.s3Text":
    "دیکھیں پیش گوئی آپ کے کھیت کے لیے کیا معنی رکھتی ہے — کب پانی دینا، چھڑکاؤ کرنا یا رکنا ہے۔",
  "solution.s4": "اپنی زبان میں پوچھیں",
  "solution.s4Text":
    "اردو، انگریزی، پنجابی اور مزید میں بات کریں یا لکھیں۔ کوئی پیچیدہ اصطلاح نہیں، کوئی اندازہ نہیں۔",
  "solution.previewLabel": "آج آپ کے فارم پر",
  "solution.preview1Label": "گندم · بونے کے 62 دن",
  "solution.preview1Value": "نشوونما کا مرحلہ: شاخیں نکلنا",
  "solution.preview2Label": "موسم",
  "solution.preview2Value": "28°C · آج رات بارش کا 40% امکان",
  "solution.preview3Label": "خطرے کی سطح",
  "solution.preview3Value": "کم — میلی بگ پر نظر رکھیں",
  "solution.preview4Label": "آج کا کام",
  "solution.preview4Value": "کل کی بارش گزرنے تک پانی دینا مؤخر کریں",
  "solution.previewNote": "نمائشی پیش نظارہ — آپ کا فارم ڈیٹا دستیاب ہونے پر دکھایا جائے گا۔",

    /* ---------- Landing: features ---------- */
  "features.eyebrow": "خصوصیات",
  "features.title": "آپ کے فارم کی ہر ضرورت، ایک جگہ",
  "features.subtitle":
    "بیمار پتے کی تشخیص سے لے کر آج کے کام طے کرنے تک، کسان اے آئی پیچیدہ کھیتی کے فیصلوں کو سادہ رہنمائی میں بدل دیتا ہے۔",
  "features.f1": "اے آئی فصل ڈاکٹر",
  "features.f1Text":
    "متاثرہ پتے کی تصویر اپ لوڈ کریں اور اعتماد، شدت اور واضح اگلے اقدامات کے ساتھ ممکنہ تشخیص حاصل کریں۔",
  "features.f2": "اے آئی اسسٹنٹ",
  "features.f2Text":
    "سادہ زبان میں اپنے فارم کے بارے میں کچھ بھی پوچھیں اور جواب اپنی فصلوں، مٹی اور موسم کی بنیاد پر حاصل کریں۔",
  "features.f3": "وائس اسسٹنٹ",
  "features.f3Text":
    "اردو، پنجابی، سرائیکی یا انگریزی میں قدرتی انداز سے بولیں — کھیت میں ٹائپنگ کی ضرورت نہیں۔",
  "features.f4": "موسمی معلومات",
  "features.f4Text":
    "سمجھیں پیش گوئی آپ کے فارم کے لیے کیا معنی رکھتی ہے — کب پانی دینا، چھڑکاؤ کرنا یا فصل کاٹنی ہے۔",
  "features.f5": "خطرات اور انتباہات",
  "features.f5Text":
    "کم، درمیانے اور زیادہ خطرات کو واضح وضاحت اور درست اقدام کے ساتھ دیکھیں۔",
  "features.f6": "آج کے کام",
  "features.f6Text":
    "آج واقعی کیا اہم ہے اس کی مختصر، ترجیحی فہرست — مزید اندازہ نہیں۔",
  "features.f7": "پیداوار کی پیش گوئی",
  "features.f7Text":
    "متوقع پیداوار کی حد اور اس کے اہم عوامل دیکھیں، تاکہ آپ فروخت اور ادویات کی منصوبہ بندی کر سکیں۔",

    /* ---------- Landing: how it works ---------- */
  "how.eyebrow": "یہ کیسے کام کرتا ہے",
  "how.title": "سیٹ اپ سے عمل تک چار آسان مراحل",
  "how.s1Title": "اپنا فارم ترتیب دیں",
  "how.s1Text":
    "اپنا مقام، فصلیں، مٹی اور بونے کی تاریخ ایک بار درج کریں — چند منٹ لگتے ہیں۔",
  "how.s2Title": "جو دیکھیں وہ شیئر کریں",
  "how.s2Text":
    "پتے کی تصویر اپ لوڈ کریں، موسم چیک کریں، یا اپنی تشویش کے بارے میں پوچھیں۔",
  "how.s3Title": "واضح جواب حاصل کریں",
  "how.s3Text":
    "آپ کی زبان میں سادہ وضاحتیں حاصل کریں، جو آپ کے فارم سے جڑی ہوں۔",
  "how.s4Title": "اعتماد سے عمل کریں",
  "how.s4Text":
    "آج کے لیے ترجیحی اقدامات کی مختصر فہرست پر عمل کریں اور اپنی پیش رفت دیکھیں۔",

    /* ---------- Landing: testimonials ---------- */
  "testimonials.eyebrow": "تاثرات",
  "testimonials.title": "کسان کسان اے آئی پر بھروسہ کرتے ہیں",
  "testimonials.subtitle": "اپنے کھیتوں میں کسان اے آئی استعمال کرنے والے کسانوں کی آوازیں۔",
  "testimonials.q1":
    "پہلے میں ہر کسی سے مشورہ لیتا تھا — پڑوسی، یوٹیوب، کبھی اجنبیوں سے بھی۔ کسان اے آئی مجھے میرے فارم کے بارے میں، میری اپنی زبان میں جواب دیتا ہے۔",
  "testimonials.n1": "محمد اسلم",
  "testimonials.r1": "گندم اور کپاس کے کسان، پنجاب",
  "testimonials.q2":
    "میرے ٹماٹر کے پتے مجھے ٹھیک لگ رہے تھے، لیکن تشخیص نے فنگس کو جلد پکڑ لیا۔ اس ایک انتباہ نے میری فصل کا بڑا حصہ بچا لیا۔",
  "testimonials.n2": "عائشہ بی بی",
  "testimonials.r2": "سبزیاں اگانے والی، سندھ",
  "testimonials.q3":
    "مجھے 'آج کے کام' کی فہرست بہت پسند ہے۔ میں صبح اسے کھولتا ہوں اور مجھے معلوم ہوتا ہے کہ کیا کرنا ہے۔ ایسا لگتا ہے جیسے میری جیب میں کوئی ماہر ہو۔",
  "testimonials.n3": "رانا عمران",
  "testimonials.r3": "چاول کے کسان، خیبر پختونخوا",
  "testimonials.stars": "5 میں سے 5 ستارے",

    /* ---------- Landing: FAQ ---------- */
  "faq.eyebrow": "سوالات",
  "faq.title": "کسانوں کے اکثر سوالات",
  "faq.subtitle": "کسان اے آئی کے بارے میں اکثر پوچھے جانے والے سوالات۔",
  "faq.q1": "کسان اے آئی کیا ہے؟",
  "faq.a1":
    "کسان اے آئی ایک اے آئی پر مبنی فارمنگ فیصلہ اسسٹنٹ ہے۔ یہ آپ کے فارم کی فصلیں، موسم، خطرات اور متوقع پیداوار کو ایک واضح تصویر میں جمع کرتا ہے — پھر آپ کو سادہ زبان میں بتاتا ہے کہ آج کیا کرنا ہے۔",
  "faq.q2": "کیا مجھے ٹیکنالوجی کا ماہر ہونا ضروری ہے؟",
  "faq.a2":
    "بالکل نہیں۔ کسان اے آئی سادہ بنایا گیا ہے: بڑے بٹن، آپ کی اپنی زبان، اور آواز سے بات کرنے کی سہولت۔ اگر آپ میسج بھیج سکتے ہیں تو کسان اے آئی استعمال کر سکتے ہیں۔",
  "faq.q3": "کون سی زبانیں سپورٹ ہوتی ہیں؟",
  "faq.a3":
    "آپ اردو، انگریزی، پنجابی اور سرائیکی میں بات یا تحریر کر سکتے ہیں، اور مزید زبانیں شامل ہو رہی ہیں۔ جواب اسی زبان میں آتے ہیں جس زبان میں آپ بات کرتے ہیں۔",
  "faq.q4": "تشخیص اور پیش گوئیاں کتنی درست ہیں؟",
  "faq.a4":
    "کسان اے آئی آپ کو فیصلے میں مدد کے لیے تخمینے اور رہنمائی دیتا ہے — کبھی کوئی ضمانت نہیں۔ آپ کو ہمیشہ اعتماد کی سطح نظر آئے گی، اور اہم معاملات میں مقامی زرعی ماہر یا ایکسٹینشن آفیسر سے تصدیق کریں۔",
  "faq.q5": "کیا میرا فارم ڈیٹا نجی ہے؟",
  "faq.a5":
    "جی ہاں۔ آپ کے فارم کی معلومات صرف آپ کی رہنمائی کو ذاتی بنانے کے لیے استعمال ہوتی ہے اور کبھی فروخت یا شیئر نہیں کی جاتی۔ آپ اپنے فارم پروفائل پر خود کنٹرول رکھتے ہیں۔",
  "faq.q6": "شروع کرنے کے لیے مجھے کیا چاہیے؟",
  "faq.a6":
    "بس اپنا فارم پروفائل بنائیں — مقام، فصلیں، مٹی اور بونے کی تاریخ۔ اس میں چند منٹ لگتے ہیں، اور پھر ہر فیچر آپ کے فارم کے مطابق ہوتا ہے۔",

    /* ---------- Landing: contact ---------- */
  "contact.eyebrow": "رابطہ",
  "contact.title": "آئیے مل کر ترقی کریں",
  "contact.subtitle":
    "سوال، شراکت کا خیال یا رائے؟ ہمیں آپ سے سننا پسند ہے — اردو، انگریزی یا کسی بھی زبان میں جس میں آپ آسانی محسوس کریں۔",
  "contact.email": "ای میل",
  "contact.phone": "فون / واٹس ایپ",
  "contact.basedIn": "مقام",
  "contact.basedInValue": "لاہور، پاکستان — ہر جگہ کے کسانوں کے لیے بنایا گیا",
  "contact.formTitle": "ہمیں پیغام بھیجیں",
  "contact.name": "آپ کا نام",
  "contact.namePlaceholder": "مثلاً احمد خان",
  "contact.emailPhone": "ای میل یا فون",
  "contact.emailPhonePlaceholder": "you@example.com یا +92 3XX XXXXXXX",
  "contact.message": "پیغام",
  "contact.messagePlaceholder": "اپنے فارم یا سوال کے بارے میں بتائیں…",
  "contact.send": "پیغام بھیجیں",
  "contact.replyNote": "ہم 1–2 کام کے دنوں میں جواب دیتے ہیں۔",
  "contact.successTitle": "شکریہ — پیغام موصول ہو گیا!",
  "contact.successText":
    "ہم نے آپ کا پیغام حاصل کر لیا ہے اور جلد آپ سے رابطہ کریں گے۔ اس دوران اپنا فارم بنائیں اور کسان اے آئی کی سہولیات دیکھیں۔",

    /* ---------- Landing: footer ---------- */
  "footer.tagline":
    "آپ کا اے آئی فارمنگ فیصلہ اسسٹنٹ — اپنے فارم کو سمجھیں اور جانیں آج کیا کرنا ہے۔",
  "footer.quickLinks": "فوری لنکس",
  "footer.product": "پروڈکٹ",
  "footer.company": "کمپنی",
  "footer.rights": "جملہ حقوق محفوظ ہیں۔",

  };
