/**
 * Phase 1 TypeScript data models.
 *
 * These interfaces describe the 12 future entities. They are used to type
 * components and state now; persistence (PostgreSQL/Supabase) comes in a
 * later phase. Every feature-carrying entity references `farmId` so the
 * architecture stays farm-centric.
 */

export type Role = "user" | "assistant";
export type Level = "low" | "medium" | "high";
export type Priority = "high" | "medium" | "low";
export type Severity = "low" | "medium" | "high";
export type GrowthStage =
  | "germination"
  | "seedling"
  | "vegetative"
  | "flowering"
  | "fruiting"
  | "maturity";

/**
 * Farm profile. `id` is the UUID generated by the Supabase `farms` table.
 * This shape matches the DB row (mapped from snake_case in the farm service).
 */
export interface Farm {
  id: string;
  farmerName: string;
  phone?: string;
  email?: string;
  location: string;
  landArea: string;
  soilType: string;
  irrigationMethod: string;
  currentCrop: string;
  currentCropVariety?: string;
  plantingDate?: string;
  createdAt: string;
}

/** Input shape for creating/updating a farm via the Farm Setup form. */
export type FarmSetupInput = Omit<Farm, "id" | "createdAt">;

export interface Crop {
  id: string;
  farmId: string;
  name: string;
  variety?: string;
  plantingDate?: string;
  growthStage?: GrowthStage;
}

export interface FarmHistory {
  id: string;
  farmId: string;
  eventType: string;
  description: string;
  date: string;
}

export interface ImageMetadata {
  format: string;
  size: number;
}

export interface CropImage {
  id: string;
  farmId: string;
  imageUrl: string;
  capturedAt: string;
  metadata: ImageMetadata;
}

export interface Diagnosis {
  id: string;
  farmId?: string;
  cropImageId?: string;
  crop: string;
  diagnosis: string;
  confidence: number;
  severity: Severity;
  description?: string;
  causes?: string[];
  recommendedActions?: string[];
  notes?: string;
  imageUrl?: string;
  createdAt: string;
}

export interface ChatConversation {
  id: string;
  farmId: string;
  language: string;
  title?: string;
  createdAt: string;
  lastMessageAt: string;
}

export interface ChatMessage {
  id: string;
  conversationId: string;
  role: Role;
  content: string;
  createdAt: string;
}

export interface WeatherForecastDay {
  date: string;
  condition: string;
  temperatureMax: number;
  temperatureMin: number;
  rainProbability: number;
  windSpeed?: number;
}

export interface WeatherSnapshot {
  id: string;
  farmId: string;
  temperature: number;
  humidity: number;
  rainProbability: number;
  windSpeed: number;
  forecast: WeatherForecastDay[];
  capturedAt: string;
}

/** Risk categories supported by the Farm Risk Engine (Prompt 8). */
export type RiskType =
  | "disease"
  | "pest"
  | "weather"
  | "irrigation"
  | "crop_stress";

/** How a risk record was produced: deterministic rules and/or AI. */
export type RiskSource = "deterministic" | "ai" | "hybrid";

/** Lifecycle of a persisted risk alert. */
export type RiskStatus = "active" | "expired" | "resolved";

export interface RiskAlert {
  id: string;
  farmId: string;
  riskType: RiskType;
  level: Level;
  title: string;
  explanation: string;
  evidence: string[];
  recommendedActions: string[];
  status: RiskStatus;
  source: RiskSource;
  createdAt: string;
  updatedAt: string;
  expiresAt?: string | null;
}

/** Result of a risk assessment run (used by the UI). */
export interface RiskAssessment {
  risks: RiskAlert[];
  assessedAt: string;
  /** Human-friendly limitations, e.g. weather or diagnoses unavailable. */
  limitations: string[];
}

/** Action categories supported by the Decision Engine (Prompt 10). */
export type ActionCategory =
  | "crop_health"
  | "weather"
  | "irrigation"
  | "pest"
  | "disease"
  | "field_inspection"
  | "growth_stage"
  | "farm_management"
  | "harvest"
  | "monitoring";

/** Timing values the Decision Engine may use (only when context supports it). */
export type ActionTiming =
  | "today"
  | "this_morning"
  | "this_afternoon"
  | "this_evening"
  | "before_rain"
  | "this_week"
  | "monitor";

/** Evidence sources that contributed to an action. */
export type ActionSource =
  | "farm_context"
  | "growth_stage"
  | "weather"
  | "diagnosis"
  | "risk"
  | "yield"
  | "history";

/**
 * A persisted "What should I do today?" action. Mirrors the `action_items`
 * table row. Every field is validated server-side by the Decision Engine —
 * nothing here is ever fabricated client-side.
 */
export interface ActionItem {
  id: string;
  farmId: string;
  /** Date (YYYY-MM-DD) the action applies to. */
  actionDate: string;
  title: string;
  description: string;
  priority: Priority;
  category: ActionCategory;
  reason: string;
  timing: ActionTiming | null;
  source: ActionSource[];
  completed: boolean;
  completedAt: string | null;
  createdAt: string;
}

/** Result of a Decision Engine run (persisted actions + honest context). */
export interface TodayActionsDecision {
  actions: ActionItem[];
  summary: string;
  limitations: string[];
  generatedAt: string;
  actionDate: string;
  /** True when the farm lacks enough info (e.g. no crop) to generate actions. */
  insufficientData: boolean;
}

export interface YieldPrediction {
  id: string;
  farmId: string;
  estimatedYield: number;
  unit: string;
  lowerBound: number;
  upperBound: number;
  confidence: number;
  keyFactors: string[];
  disclaimer: string;
  createdAt: string;
}

export interface VoiceSession {
  id: string;
  farmId: string;
  language: string;
  transcript?: string;
  audioUrl?: string;
  createdAt: string;
}

/* ------------------------------------------------------------------ */
/* Phase 3 — Growth Stage Engine + Farm Context                        */
/* ------------------------------------------------------------------ */

/**
 * Growth stages supported by the deterministic growth-stage engine.
 * `unknown` / `not_started` are safe fallbacks used instead of ever
 * inventing a scientifically precise stage we don't have config for.
 */
export type CropGrowthStage =
  | "germination"
  | "vegetative"
  | "flowering"
  | "fruiting"
  | "maturity"
  | "harvest"
  | "unknown"
  | "not_started";

/** One stage boundary of a crop's growth cycle (inclusive day range). */
export interface CropStageBoundary {
  stage: Exclude<CropGrowthStage, "unknown" | "not_started">;
  label: string;
  /** Inclusive first day of crop age for this stage. */
  startDay: number;
  /** Inclusive last day of crop age for this stage. */
  endDay: number;
}

/**
 * Reusable growth configuration for one crop. Boundaries are MVP estimates,
 * intentionally modular so agricultural rules can be refined later without
 * touching the engine or any UI component.
 */
export interface CropGrowthConfig {
  /** Canonical crop key, e.g. "wheat". */
  crop: string;
  /** Human-readable label, e.g. "Wheat". */
  label: string;
  /** Reference full-cycle length in days (informational). */
  totalDays: number;
  /** Ordered stage boundaries covering the whole cycle. */
  stages: CropStageBoundary[];
}

/** Deterministic growth result — never fake, always derived from saved data. */
export interface CropGrowthInfo {
  crop: string;
  /** Days since planting; null when there is no valid planting date. */
  cropAgeDays: number | null;
  growthStage: CropGrowthStage;
  stageLabel: string;
  confidence: "estimated" | "unknown";
  reason?: string;
}

/** Crop portion of the Farm Context (mirrors the Farm profile fields). */
export interface FarmContextCrop {
  name: string;
  variety: string | null;
  plantingDate: string | null;
}

/**
 * Reusable Farm Context consumed by every future Kissan AI feature so they
 * share one source of farm + crop + growth information instead of each
 * independently querying `farms` and re-deriving crop age.
 */
export interface FarmContext {
  farm: Farm;
  crop: FarmContextCrop;
  growth: CropGrowthInfo;
}

export type FarmContextStatus =
  | "loading"
  | "ready"
  | "no_farm"
  | "not_found"
  | "error";

/** Result shape for the async Farm Context loader (never throws to the UI). */
export interface FarmContextResult {
  status: FarmContextStatus;
  context: FarmContext | null;
  message?: string;
}

/* ------------------------------------------------------------------ */
/* Phase 13 — Smart Crop Recommendation                               */
/* ------------------------------------------------------------------ */

/**
 * Estimated suitability of a recommended crop. Advisory — never a guarantee
 * of yield or profit (the AI is instructed to keep this as an estimate).
 */
export type CropSuitability = "high" | "moderate" | "low";

/**
 * One recommended crop (Prompt 13). Mirrors the validated items returned by
 * the `recommend-crops` Edge Function and stored in the jsonb
 * `recommendations` column of `crop_recommendations`.
 */
export interface CropRecommendation {
  crop: string;
  suitability: CropSuitability;
  /** 0–100 AI self-assessed confidence, shown separately from suitability. */
  confidence: number;
  whySuitable: string;
  soilFit: string;
  waterRequirement: string;
  weatherFit: string;
  keyConsiderations: string[];
}

/**
 * A persisted recommended-crops run. Mirrors a `crop_recommendations` row
 * (mapped from snake_case columns). Every record is owned by a farm and was
 * produced by the real AI Edge Function from real farm context — never fake.
 */
export interface CropRecommendationRecord {
  id: string;
  farmId: string;
  recommendations: CropRecommendation[];
  summary: string;
  limitations: string[];
  needsMoreInformation: boolean;
  missingInformation: string[];
  createdAt: string;
}

/* ------------------------------------------------------------------ */
/* Phase 14 — Irrigation Advisor                                       */
/* ------------------------------------------------------------------ */

/**
 * Overall irrigation recommendation for a farm right now. The labels are
 * advisory — they answer "when/how much should I irrigate" using real farm,
 * growth, and (when live) weather data. `insufficient` is an honest state
 * returned when critical context (crop, soil, irrigation method) is missing
 * rather than inventing guidance.
 */
export type IrrigationStatus =
  | "irrigate_now"
  | "irrigation_soon"
  | "delay"
  | "adequate"
  | "insufficient";

/** How much weight should be attached to the recommendation. */
export type IrrigationUrgency = "low" | "medium" | "high";

/**
 * A validated irrigation advisory result (Prompt 14). Produced server-side by
 * the `irrigation-advisor` Edge Function from REAL farm context + growth stage
 * + (when available) live weather. Water amounts are only ever provided with
 * confidence when the available data genuinely supports an estimate; otherwise
 * the system returns relative guidance and says the exact quantity cannot be
 * reliably estimated.
 */
export interface IrrigationRecommendation {
  /** Overall status for the farm right now. */
  status: IrrigationStatus;
  urgency: IrrigationUrgency;
  /** Plain language headline recommendation. */
  recommendation: string;
  /** When to irrigate (timing guidance). */
  timing?: { recommended_time: string; reason: string } | null;
  /**
   * Water quantity guidance. `amount` is null when the exact figure cannot be
   * responsibly estimated from available data. `unit` accompanies amount.
   * `confidence` is 0–100 the model's confidence in the quantity estimate.
   */
  waterGuidance: { amount: string; unit: string; confidence: number; relative: string };
  weatherImpact: string;
  soilImpact: string;
  cropStageImpact: string;
  rainAdjustment: string;
  nextCheck: string;
  importantNotes: string[];
  limitations: string[];
}

/** A persisted irrigation-advisor run. Mirrors an `irrigation_recommendations` row. */
export interface IrrigationRecommendationRecord {
  id: string;
  farmId: string;
  recommendation: IrrigationRecommendation;
  summary: string;
  limitations: string[];
  needsMoreInformation: boolean;
  missingInformation: string[];
  createdAt: string;
}